### ISSUE TITLE
Timer Stops When It Shouldn't

### ISSUE THREAD

**Issue by ester245** [ashokkumar9892/patient-app-Backup#138]
As soon as I enter into patient's account the timer should start and stay going as long as I am in it. As soon as I clicked on Clinical Data it stopped. Can you please fix that?

**Comment by ashokkumar9892** [comment]
Timer should not restart while clicking on tab

**Comment by ashokkumar9892** [comment]
not fix.  not deployed code.

**Comment by sahil2567** [comment]
i have fixed this.
