### ISSUE TITLE
CareCoordination Task Type Not Working with Time Log

### ISSUE THREAD

**Issue by ester245** [ashokkumar9892/patient-app-Backup#140]
I just chose Care Coordination as task type for a patient I just spent 16:50 minutes with. I pressed the Add Time Log button and it did not transfer into the Time Log. Please check this when you can. I am currently trying to enter time amounts for each patient as I am working with them.

**Comment by ester245** [comment]
It did not work for me when I was on Bertha Ridley's account, but now it did work on another patient a minute ago.

**Comment by bhashkar123** [comment]
i think now it is working with Ridley, Bertha;;;now you can chek

**Comment by bhashkar123** [comment]
now its working for Ridley, Bertha, you can chek
