### ISSUE TITLE
Login admin -note for patient non updation

### ISSUE THREAD

**Issue by Abhishek23005** [ashokkumar9892/patient-app-Backup#92]
mostly patient not updating note for patient- below list.
1-Abhisept23005 2-Abhishek1pandey 3-Ashok kumar 4-dafasgertg  5-fxygtfghc  6-gtyfrtde  7-Jaypal  8- kydkes122 
9-lalalal  10-Mdtrail  11-pintuiio  12- prakash  13-priya    14-rahul verma   15- sdiajdfiouad  16- siddharth sinhav6reews5ew

**Comment by ashokkumar9892** [comment]
This also fixed
